/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.taller.vistas;

import com.mycompany.taller.entidades.Bicicleta;
import com.mycompany.taller.entidades.Cliente;
import com.mycompany.taller.persistencia.BicicletaData;
import com.mycompany.taller.persistencia.ClienteData;
import com.mycompany.taller.persistencia.Conexion;
import com.mycompany.taller.persistencia.ReparacionData;
import com.mycompany.taller.persistencia.ServicioData;
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author ezequ
 */
public class VistaReparacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaReparacion
     */
//    
//    private ClienteData cData;
//    private BicicletaData bData;
//    private ServicioData sData;
    
    Connection conexiondb = Conexion.getConexion();
    ReparacionData reData = new ReparacionData(conexiondb);
    ClienteData cData =  new ClienteData(conexiondb);
    BicicletaData bData = new BicicletaData(conexiondb);
    ServicioData sData = new ServicioData(conexiondb);
    public VistaReparacion() {
        initComponents();
//        this.bData = new BicicletaData(conexiondb);
//        this.sData = new ServicioData(conexiondb);
//        this.cData = new ClienteData(conexiondb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLid = new javax.swing.JLabel();
        JLcliente = new javax.swing.JLabel();
        JLservicio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLpreciofinal = new javax.swing.JLabel();
        JLfechadeentrada = new javax.swing.JLabel();
        JBagregar = new javax.swing.JButton();
        JBactualizar = new javax.swing.JButton();
        JCBservicio = new javax.swing.JComboBox<>();
        JTFid = new javax.swing.JTextField();
        JCBestado = new javax.swing.JCheckBox();
        JTFpreciofinal = new javax.swing.JTextField();
        JDCfechadeentrada = new com.toedter.calendar.JDateChooser();
        JBlimpiar = new javax.swing.JButton();
        JBbuscarReparacion = new javax.swing.JButton();
        JTFcliente = new javax.swing.JTextField();
        JBbuscarCliente = new javax.swing.JButton();
        JLbicicleta = new javax.swing.JLabel();
        JCBbicicleta = new javax.swing.JComboBox<>();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Gestión de reparación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Constantia", 0, 16))); // NOI18N

        JLid.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        JLid.setText("N° de reparación");

        JLcliente.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        JLcliente.setText("Cliente");

        JLservicio.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        JLservicio.setText("Servicio");

        jLabel4.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel4.setText("Estado");

        JLpreciofinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JLpreciofinal.setText("Precio");

        JLfechadeentrada.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        JLfechadeentrada.setText("Fecha de entrada");

        JBagregar.setText("Agregar");

        JBactualizar.setText("Actualizar");

        JTFid.setEditable(false);
        JTFid.setEnabled(false);

        JTFpreciofinal.setEditable(false);
        JTFpreciofinal.setEnabled(false);

        JBlimpiar.setText("Limpiar");

        JBbuscarReparacion.setText("Buscar");

        JBbuscarCliente.setText("Buscar");
        JBbuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbuscarClienteActionPerformed(evt);
            }
        });

        JLbicicleta.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        JLbicicleta.setText("Bicicleta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(JBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBbuscarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JLcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBbuscarCliente)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLservicio)
                                    .addComponent(JLbicicleta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCBbicicleta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JCBservicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JLfechadeentrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JDCfechadeentrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JLpreciofinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFpreciofinal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCBestado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JLid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLid)
                    .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLcliente)
                    .addComponent(JTFcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBbuscarCliente))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbicicleta)
                    .addComponent(JCBbicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLservicio)
                            .addComponent(JCBservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLpreciofinal)
                            .addComponent(JTFpreciofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(JLfechadeentrada))
                    .addComponent(JDCfechadeentrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(JCBestado))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBagregar)
                    .addComponent(JBactualizar)
                    .addComponent(JBbuscarReparacion)
                    .addComponent(JBlimpiar))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBbuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbuscarClienteActionPerformed
        Cliente cliente = cData.buscarClientePorDni(Long.parseLong(JTFcliente.getText()));
        ArrayList<Bicicleta> biciLista = bData.buscarBicicletaPorCliente(cliente.getId());
        for (Bicicleta aux : biciLista) {
            JCBbicicleta.addItem(aux);
        }
    }//GEN-LAST:event_JBbuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBactualizar;
    private javax.swing.JButton JBagregar;
    private javax.swing.JButton JBbuscarCliente;
    private javax.swing.JButton JBbuscarReparacion;
    private javax.swing.JButton JBlimpiar;
    private javax.swing.JComboBox<Bicicleta> JCBbicicleta;
    private javax.swing.JCheckBox JCBestado;
    private javax.swing.JComboBox<String> JCBservicio;
    private com.toedter.calendar.JDateChooser JDCfechadeentrada;
    private javax.swing.JLabel JLbicicleta;
    private javax.swing.JLabel JLcliente;
    private javax.swing.JLabel JLfechadeentrada;
    private javax.swing.JLabel JLid;
    private javax.swing.JLabel JLpreciofinal;
    private javax.swing.JLabel JLservicio;
    private javax.swing.JTextField JTFcliente;
    private javax.swing.JTextField JTFid;
    private javax.swing.JTextField JTFpreciofinal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
